export const routes = {
    home: '/',
    desayuno: '/desayuno',
    almuerzo: '/almuerzo',
    mediatarde:'/merienda',
    cena: '/cena',
    detail: '/recipe/:id',
    detailTest: '',
    adminPanel: '/administracion/',
    crearReceta: '/administracion/crear',
    register: '/register',
    login: '/login',
    myAccount: '/myAccount',
    favs: '/favoritos',
    planner: '/planificador',
}
